name: Destroy Terraform

on:
  push:
    branches:
      - main

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      #  with:
    #      terraform_version: <version> # Specify the version of Terraform you want to use

      - name: Terraform init
        run: terraform init

      - name: Terraform destroy
        run: terraform destroy -auto-approve
